### ISSUE TITLE
Prepare materials for Hackaton

### ISSUE THREAD

**Issue by chcorbato** [remaro-network/tudelft_hackathon#19]
-[] Make list
-[] Acquire materials

**Comment by Rezenders** [comment]
- Tents (big enough to fit all of us + robots + laptops)
- Extension cords or power generator (I still need to figure out where we can connect those)
- Wifi routers (I think this would be useful, but I am not sure if it is strictly necessary, probably not)*
- Tables & Chairs (just "get" somewhere in the faculty)
	
Printed bluerov pre dive checklists
	
[Bike flag](https://www.bol.com/nl/nl/p/dresco-fietsvlag-oranje/9200000058955351/?Referrer=ADVNLGOO002066-G-110131505903-S-677125984306-9200000058955351&gclid=CjwKCAjw7cGUBhA9EiwArBAvohTFnITvBWCNJP0VfRMaW8tbgGFyLlzGtXEI2127VnMYnaIvF5Q8nBoC2IcQAvD_BwE) (to know where the robot is underwater)

list:
- packing list (pack on the day prior)
- check list of todos
- picture of the location
- responsibilities (Important)
- planning of the day, times, tasks, who does what tests
- procedures details
-

**Comment by Rezenders** [comment]
Packing list:
1. Bluerov2
2. Fathom Tether with Spool
3. Fathom ROV Tether used to connect the Spool with Topside Interface
4. Topside Interface
5. USB-A to USB-B cable
6. Bag with tools (this can be further detailed)
7. Hex tool set
8. 2x Batteries
9. Vacuum pump
10. Xbox joystick
11. Xbox joystick usb cable
12. Add-on "stick" to know where the robot is
13. Extension cords

**Comment by Rezenders** [comment]
Picture of location:
![image](https://user-images.githubusercontent.com/20564040/173861429-c6d3c0b1-9962-4f02-8f23-c4b1be9987c9.png)

**Comment by tvanenckevort** [comment]
Material:

- Tents (big enough to fit all of us + robots + laptops) If it is raining. We can hire here: [partyverhuren](https://partyverhuren.nl/product/partytent-easyup-3x3-wit/) or here: [rozema](https://www.rozemaverhuur.nl/product/overkapping-300-x-300-cm-ez-up/) or buy here: [gamma](https://www.gamma.nl/assortiment/partytent-caribe-grijs/p/B355449) or here: [hornbach](https://www.hornbach.nl/shop/GARDEN-PLACE-Partytent-wit-3-x-3-m/3808932/artikel.html)
- Extension cords (can be connected via window at dcsc hall) get these somewhere at the faculty?
- Wifi routers (not needed, there is eduroam)
- Tables & Chairs (we can use the picknick tables at the pond)
- Printed bluerov pre dive checklists
- [Bike flag](https://www.bol.com/nl/nl/p/dresco-fietsvlag-oranje/9200000058955351/?Referrer=ADVNLGOO002066-G-110131505903-S-677125984306-9200000058955351&gclid=CjwKCAjw7cGUBhA9EiwArBAvohTFnITvBWCNJP0VfRMaW8tbgGFyLlzGtXEI2127VnMYnaIvF5Q8nBoC2IcQAvD_BwE) (to know where the robot is underwater) or use the aluminium rod that is used right now, might need to make a little flag or arrow to point towards robot forward axis

**Comment by tvanenckevort** [comment]
Checklist for the Hackathon: (@Rezenders please add anything I've forgotten)

Before the test:
- Set up tent 
- run powercord through window
- set up any tables and chairs (if needed)
- clean the place/floor beforehand
- arrange some towels/hand sanitizers/etc. so people can clean/dry hands after taking robot out of water 
- attach flag/tu delft coffee cup to the pole on the bluerov

To test:
- test seals of bluerov by putting it under vacuum
- connect all the tethers etc to the bluerov and the laptop
- disarm the bluerov
- place the bluerov in water
- arm the bluerov and test thruster
- run code 
- disarm bluerov
- pick bluerov out of water

after test:
- tidy up tents/chairs/tables etc
- tidy up extension cords
- tidy up the bluerov
