### ISSUE TITLE
Minilecture "ROS2"

### ISSUE THREAD

**Issue by chcorbato** [remaro-network/tudelft_hackathon#22]
Very minimal intro to the ROS2 concepts and tools required for the Hackaton.
Also, we need to recommend preparation activities, e.g. if they are new to ROS, a guided introduction is week 1 of:
https://online-learning.tudelft.nl/courses/hello-real-world-with-ros-robot-operating-systems/

**Comment by Rezenders** [comment]
I am going to close this, since we have everything needed.
