### ISSUE TITLE
Minilecture "Sonar"

### ISSUE THREAD

**Issue by chcorbato** [remaro-network/tudelft_hackathon#23]
30min
Contents:
- theory how it works
- details of the specific sonar we use
- add general about other sonars
- issues using sonar
Thanks to the lecture, students should be able to figure out how to use the sonar and its data, e.g. understand this message type fields of the sonar driver used in the hackathon (or the one we actually use, Gustavo can clarify):
https://github.com/CentraleNantesRobotics/ping360_sonar/blob/ros2/ping360_sonar_msgs/msg/SonarEcho.msg

**Comment by Rezenders** [comment]
I am going to close this, since we have everything needed.
