### ISSUE TITLE
Ignition error: Unable to create the rendering window: OGRE EXCEPTION(3:RenderingAPIException): OpenGL 3.3 is not supported.

### ISSUE THREAD

**Issue by olayasturias** [remaro-network/tudelft_hackathon#32]
When running ignition from dockerfile with
`ign gazebo shapes.sdf`
or
`ign gazebo -v 3 -r underwater.world`

I get the following error:
`[GUI] [Err] [Ogre2RenderEngine.cc:991]  Unable to create the rendering window: OGRE EXCEPTION(3:RenderingAPIException): OpenGL 3.3 is not supported. Please update your graphics card drivers. in GL3PlusRenderSystem::initialiseContext at /var/lib/jenkins/workspace/ogre-2.2-debbuilder/repo/RenderSystems/GL3Plus/src/OgreGL3PlusRenderSystem.cpp (line 3364)`

Which is strange because I didn't get this error when launching from previous versions of the dockerfile

**Comment by olayasturias** [comment]
According to the answer [ here](https://answers.gazebosim.org/question/27597/ignition-crashes-directly-after-start/), it launches without errors as:
`ign gazebo -v 3 -r underwater.world --render-engine ogre`
or:
`ign gazebo shapes.sdf --render-engine ogre`
It argues that the error is due to:

> Ignition Fortress trying to use the Ogre2 render engine which requires OpenGL > 3.3, but my machine was stuck using OpenGL 3.1

**Comment by jpcoffelt** [comment]
I got the same error when trying to launch
`ign gazebo shapes.sdf`
from a virtual machine (Ubuntu 20 in Oracle VirtualBox 6.1).

`--render-engine ogre`
also allowed launching without errors (but at a terrible resolution).

Typical GPU issues with virtual machines. :-(

**Comment by Rezenders** [comment]
I guess we need to maintain 2 separate images, one for Nvidia and one for the rest. Just installing mesa and passing some args when running the image should be enough. I will work on this. 
For the vscode plugin I 
Check these links:
- http://wiki.ros.org/docker/Tutorials/Hardware%20Acceleration
- https://www.reddit.com/r/docker/comments/cl9qut/hardwareagnostic_way_to_run_gpuaccelerated_opengl/

**Comment by Rezenders** [comment]
I added a docker image for non-nvidia systems. 
Now we have 2 different images:
- `rezenders/ignition:hackathon-nvidia`
- `rezenders/ignition:hackathon-non-nvidia`

It is necessary to pass the right args when running it, something like [this](https://github.com/remaro-network/tudelft_hackathon/tree/ros2/dockerfiles/ignition-non-nvidia)

I didn't test running it in a non-nvidia system because I don't have one available. @martinaub said he can test in an AMD system.

**Comment by Rezenders** [comment]
@martinaub tested and it worked for AMD. I am closing this issue.
