### ISSUE TITLE
Clarifications for Local Install instructions

### ISSUE THREAD

**Issue by jpcoffelt** [remaro-network/tudelft_hackathon#33]
In the "Install ardusub" step [here](https://github.com/remaro-network/tudelft_hackathon/#install-ardusub), is "recursive" or "recurse-submodule" meant instead of "recurse" in:
``git clone https://github.com/ArduPilot/ardupilot.git -b Sub-4.1 --recurse``

Following the instructions [here](https://ardupilot.org/dev/docs/building-setup-linux.html#building-setup-linux), do we stop at the ``. ~/.profile`` step or do we continue with the waf build described [here](https://github.com/ArduPilot/ardupilot/blob/master/BUILD.md)?

**Comment by jpcoffelt** [comment]
Also, when trying to run locally, this step:
``sim_vehicle.py -L RATBeach -v ArduSub --model=JSON --out=udp:0.0.0.0:14550 --console``
gives the error:
``No such file or directory: 'mavproxy.py'``
as shown below:
![mavproxy](https://user-images.githubusercontent.com/47064066/174990330-cdfa7b82-5ebf-4369-a43d-f1099c4b9ef7.png)

**Comment by Rezenders** [comment]
> In the "Install ardusub" step [here](https://github.com/remaro-network/tudelft_hackathon/#install-ardusub), is "recursive" or "recurse-submodule" meant instead of "recurse" in:
> git clone https://github.com/ArduPilot/ardupilot.git -b Sub-4.1 --recurse

`--recurse`, `--recurse-submodules`, and `--recursive` are aliases and have the same behavior. But I will change it to `--recurse-submodules` to avoid confusion

> No such file or directory: 'mavproxy.py'

Did you use this script to install everything? `Tools/environment_install/install-prereqs-ubuntu.sh -y`

Can you check it the contents of the `profile` file to see if autopilot is there? With this command ` cat ~/.profile`
in the end of the file it should have something like this:
```
export PATH=/opt/gcc-arm-none-eabi-10-2020-q4-major/bin:$PATH
export PATH=/home/gus/Documents/git/ardupilot/Tools/autotest:$PATH
export PATH=/usr/lib/ccache:$PATH
export PATH=/opt/gcc-arm-none-eabi-6-2017-q2-update/bin:$PATH
```

Can you check if running only  `mavproxy.py --version` works?

Stopping at `. ~/.profile` should be enough

**Comment by jpcoffelt** [comment]
Thanks for the clarification on `--recurse`. That's what I assumed, but I couldn't find it in online documentation or CL help.

It turns out the install script you mentioned was aborting without any notification. There were several issues on my side. First other repo signtares and keys were causing `apt update` to terminate with errors. Other issue was OS python, Blender python, and Anaconda were conflicting and causing `pip3` to fail. Changing to `pip` in the installation script fixed that.

There may be other issues, but the installation script did finally run successfully to completion.
